# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eridauni
email: QuickScythe@gmail.com
description: This is the site for the Eridani Minecraft server. Feel free to post questions in the forums, and message us on our various social media sites.

url: "http://eridauni.github.io/" # the base hostname & protocol for your site
twitter_username: QuickScythe_Gaming
github_username:  QuickScythe
youtube_username: QuickScythe_Gaming
codepen_username: Sky_General109


pages:
  -Shop
  -Stats
# Build settings
markdown: kramdown

